// Mirrors the protocol field mappings in handler/apimart_image.go and apimart_video.go.
export type APIMartInputConfig = {
    aspectField?: string;
    imageRefKind?: string;
    videoRefField?: string;
    videoRefKind?: string;
    audioRefField?: string;
    audioRefKind?: string;
    imageRefField?: string;
    dropAspectWithImage?: boolean;
    maxImageRefs?: number;
    maxResolution?: string;
    resolutionCase?: string;
    hasResolution?: boolean;
    modeFromRes?: boolean;
    durationField?: string;
    hasQuality?: boolean;
    hasOutput?: boolean;
    hasCount?: boolean;
    minResolution?: string;
};
export function teamAPIMartVideoConfig(model: string): APIMartInputConfig {
    model = model.toLowerCase().replace(/[._/ ]/g, "-");
    const config: APIMartInputConfig = {"aspectField": "aspect_ratio", "durationField": "duration", "hasResolution": true, "resolutionCase": "video", "imageRefField": "image_urls", "imageRefKind": "array"};
    if (model.includes("seedance-2")) Object.assign(config, {"aspectField": "size", "imageRefKind": "seedance2", "videoRefField": "video_urls", "videoRefKind": "array", "audioRefField": "audio_urls", "audioRefKind": "array"});
    else if (model.includes("seedance-1")) Object.assign(config, {"aspectField": "aspect_ratio", "imageRefField": "image_with_roles", "imageRefKind": "roles"});
    else if (model.includes("sora-2-pro")) Object.assign(config, {"aspectField": "aspect_ratio", "dropAspectWithImage": true, "maxImageRefs": 1});
    else if (model.includes("sora-2")) Object.assign(config, {"aspectField": "aspect_ratio", "maxResolution": "720p", "dropAspectWithImage": true, "maxImageRefs": 1});
    else if (model.includes("veo") && model.includes("official")) Object.assign(config, {"aspectField": "aspect_ratio", "imageRefField": "first_frame_image", "imageRefKind": "first_last"});
    else if (model.includes("veo")) Object.assign(config, {"aspectField": "aspect_ratio"});
    else if (model == "minimax-h3") Object.assign(config, {"aspectField": "aspect_ratio", "imageRefField": "image_urls", "imageRefKind": "minimax_h3", "videoRefField": "video_urls", "videoRefKind": "array", "audioRefField": "audio_urls", "audioRefKind": "array"});
    else if (model.includes("minimax-hailuo-2-3")) Object.assign(config, {"aspectField": "", "imageRefField": "first_frame_image", "imageRefKind": "first_only"});
    else if (model.includes("minimax") || model.includes("hailuo")) Object.assign(config, {"aspectField": "", "imageRefField": "first_frame_image", "imageRefKind": "first_last"});
    else if (model.includes("skyreels")) Object.assign(config, {"aspectField": "aspect_ratio", "imageRefField": "first_frame_image", "imageRefKind": "skyreels", "videoRefField": "ref_videos", "videoRefKind": "skyreels", "audioRefKind": "skyreels_ref_images"});
    else if (model == "kling-3-0-turbo") Object.assign(config, {"aspectField": "aspect_ratio", "imageRefField": "first_frame_image", "imageRefKind": "first_only", "dropAspectWithImage": true});
    else if (model == "happyhorse-1-1") Object.assign(config, {"aspectField": "size", "resolutionCase": "upper_video", "imageRefKind": "happyhorse11"});
    else if (model.includes("happyhorse")) Object.assign(config, {"aspectField": "size", "resolutionCase": "upper_video", "imageRefKind": "happyhorse", "videoRefField": "video_url", "videoRefKind": "single"});
    else if (model.includes("gemini-omni-flash-preview")) Object.assign(config, {"maxResolution": "720p", "videoRefField": "video_urls", "videoRefKind": "array"});
    else if (model.includes("wan2-7-r2v") || model.includes("wan2.7-r2v")) Object.assign(config, {"aspectField": "size", "resolutionCase": "upper_video", "imageRefField": "image_with_roles", "imageRefKind": "roles", "videoRefField": "video_urls", "videoRefKind": "array", "audioRefKind": "wan_r2v_voice"});
    else if (model.includes("wan2-7-videoedit") || model.includes("wan2.7-videoedit")) Object.assign(config, {"aspectField": "size", "resolutionCase": "upper_video", "videoRefField": "video_urls", "videoRefKind": "array"});
    else if (model.includes("wan2-7") || model.includes("wan2.7")) Object.assign(config, {"aspectField": "size", "resolutionCase": "upper_video", "imageRefField": "image_with_roles", "imageRefKind": "roles", "videoRefField": "video_urls", "videoRefKind": "array", "audioRefField": "audio_url", "audioRefKind": "single"});
    else if (model.includes("wan2-6-i2v-flash") || model.includes("wan2.6-i2v-flash")) Object.assign(config, {"aspectField": "", "audioRefField": "audio_url", "audioRefKind": "single"});
    else if (model.includes("wan2-5") || model.includes("wan2.5")) Object.assign(config, {"aspectField": "size", "dropAspectWithImage": true, "audioRefField": "audio_url", "audioRefKind": "single"});
    else if (model.includes("wan2-6") || model.includes("wan2.6")) Object.assign(config, {"aspectField": "aspect_ratio", "dropAspectWithImage": true, "audioRefField": "audio_url", "audioRefKind": "single"});
    else if (model.includes("kling-v2-6-motion") || model.includes("motion-control")) Object.assign(config, {"aspectField": "", "hasResolution": false, "imageRefField": "image_url", "imageRefKind": "single", "videoRefField": "video_url", "videoRefKind": "single"});
    else if (model.includes("kling-v2-6") || model.includes("kling-2-6")) Object.assign(config, {"aspectField": "aspect_ratio", "hasResolution": false, "imageRefKind": "array_frames"});
    else if (model == "kling-v3") Object.assign(config, {"aspectField": "aspect_ratio", "hasResolution": false, "imageRefKind": "array_frames"});
    else if (model.includes("kling-v3-omni") || model.includes("kling-video-o1")) Object.assign(config, {"aspectField": "aspect_ratio", "hasResolution": false, "modeFromRes": true, "videoRefField": "video_list", "videoRefKind": "kling_video_list"});
    else if (model.includes("kling")) Object.assign(config, {"aspectField": "aspect_ratio", "hasResolution": false, "modeFromRes": true});
    else if (model.includes("vidu")) Object.assign(config, {"aspectField": "aspect_ratio", "imageRefKind": "array_frames"});
    else if (model.includes("grok-imagine")) Object.assign(config, {"aspectField": "aspect_ratio"});
    else if (model.includes("pixverse")) Object.assign(config, {"aspectField": "size", "imageRefKind": "pixverse"});
    else if (model.includes("omni-flash")) Object.assign(config, {"aspectField": "aspect_ratio", "videoRefField": "video_urls", "videoRefKind": "array"});
    else if (model.includes("flux-3-video")) Object.assign(config, {"aspectField": "aspect_ratio", "hasResolution": true, "resolutionCase": "video", "maxImageRefs": 10, "imageRefField": "image_urls", "imageRefKind": "array", "videoRefField": "video_url", "videoRefKind": "single"});
    return config;
}
export function teamAPIMartImageConfig(model: string): APIMartInputConfig {
    model = model.toLowerCase().replace(/[._/ ]/g, "-");
    const config: APIMartInputConfig = {"aspectField": "size", "hasResolution": true, "resolutionCase": "upper", "hasCount": true, "imageRefField": "image_urls", "imageRefKind": "array"};
    if (model.includes("gpt-image-2") && model.includes("official")) Object.assign(config, {"resolutionCase": "lower", "hasQuality": true, "hasOutput": true});
    else if (model.includes("gpt-image-2")) Object.assign(config, {"resolutionCase": "lower", "hasQuality": true, "hasOutput": false});
    else if (model.includes("gpt-4o-image")) Object.assign(config, {"hasResolution": false});
    else if (model.includes("gpt-image-1")) Object.assign(config, {"hasResolution": false, "hasQuality": true, "hasOutput": true});
    else if (model.includes("gemini-3-1-flash-lite")) Object.assign(config, {"resolutionCase": "upper", "maxResolution": "1K"});
    else if (model.includes("gemini-3-1") || model.includes("gemini-31") || model.includes("nano-banana2")) Object.assign(config, {"resolutionCase": "upper", "hasCount": false});
    else if (model.includes("gemini-3-pro") || model.includes("nano-banana-pro")) Object.assign(config, {"resolutionCase": "upper", "hasCount": false});
    else if (model.includes("gemini-2-5") || model.includes("nano-banana")) Object.assign(config, {"resolutionCase": "upper", "maxResolution": "1K", "hasCount": false});
    else if (model.includes("imagen")) Object.assign(config, {"hasResolution": false, "hasQuality": false, "hasCount": false, "imageRefField": ""});
    else if (model.includes("seedream-5-0-pro")) Object.assign(config, {"resolutionCase": "upper", "maxResolution": "2K", "hasCount": false, "maxImageRefs": 10});
    else if (model.includes("seedream-5")) Object.assign(config, {"resolutionCase": "upper", "minResolution": "2K", "hasOutput": true});
    else if (model.includes("seedream-4-5") || model.includes("seedance-4-5")) Object.assign(config, {"resolutionCase": "upper", "minResolution": "2K"});
    else if (model.includes("seedream") || model.includes("seedance-4")) Object.assign(config, {"resolutionCase": "upper"});
    else if (model.includes("qwen")) Object.assign(config, {"resolutionCase": "upper", "maxResolution": "2K"});
    else if (model.includes("z-image")) Object.assign(config, {"resolutionCase": "upper", "maxResolution": "2K", "hasCount": false, "imageRefField": ""});
    else if (model.includes("grok-imagine")) Object.assign(config, {"hasResolution": false});
    else if (model.includes("wan2-7") || model.includes("wan2.7")) Object.assign(config, {"resolutionCase": "upper"});
    else if (model.includes("flux-2")) Object.assign(config, {"resolutionCase": "upper", "hasCount": false});
    return config;
}
