// Field mappings mirror handler/kie_video.go; used only for team proxy requests.
export type KIEInputConfig = {
    aspectField?: string;
    durationKind?: string;
    hasResolution?: boolean;
    imageRefField?: string;
    imageRefKind?: string;
    videoRefField?: string;
    videoRefKind?: string;
    audioRefField?: string;
    audioRefKind?: string;
    durationMin?: number;
    durationMax?: number;
    allowAutoDuration?: boolean;
    resolutionKind?: string;
    presetField?: string;
    aspectKind?: string;
    resolutionField?: string;
    countField?: string;
    maxResolution?: string;
    hasOutputFormat?: boolean;
    hasQuality?: boolean;
    countKind?: string;
};
export const teamKIEInputConfigs: Record<string, KIEInputConfig> = {
    "bytedance/seedance-1.5-pro": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "input_urls","imageRefKind": "array"},
    "bytedance/seedance-2": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image_urls","imageRefKind": "array","videoRefField": "reference_video_urls","videoRefKind": "array","audioRefField": "reference_audio_urls","audioRefKind": "array"},
    "bytedance/seedance-2-fast": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image_urls","imageRefKind": "array","videoRefField": "reference_video_urls","videoRefKind": "array","audioRefField": "reference_audio_urls","audioRefKind": "array"},
    "bytedance/seedance-2-mini": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image_urls","imageRefKind": "array","videoRefField": "reference_video_urls","videoRefKind": "array","audioRefField": "reference_audio_urls","audioRefKind": "array"},
    "bytedance/seedance-2-5": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 4,"durationMax": 30,"allowAutoDuration": true,"hasResolution": true,"resolutionKind": "seedance_2_5_video","imageRefField": "reference_image_urls","imageRefKind": "array","videoRefField": "reference_video_urls","videoRefKind": "array","audioRefField": "reference_audio_urls","audioRefKind": "array"},
    "bytedance/v1-lite-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_url","imageRefKind": "single"},
    "bytedance/v1-lite-text-to-video": {"aspectField": "aspect_ratio","durationKind": "string","hasResolution": true},
    "bytedance/v1-pro-fast-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_url","imageRefKind": "single"},
    "bytedance/v1-pro-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_url","imageRefKind": "single"},
    "bytedance/v1-pro-text-to-video": {"aspectField": "aspect_ratio","durationKind": "string","hasResolution": true},
    "gemini-omni-video": {"aspectField": "aspect_ratio","durationKind": "string","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array","videoRefField": "video_list","videoRefKind": "gemini_video_list","audioRefField": "audio_ids","audioRefKind": "array"},
    "grok-imagine/image-to-video": {"aspectField": "aspect_ratio","durationKind": "string","durationMin": 6,"durationMax": 30,"hasResolution": true,"presetField": "mode","imageRefField": "image_urls","imageRefKind": "array"},
    "grok-imagine/text-to-video": {"aspectField": "aspect_ratio","durationKind": "string","durationMin": 6,"durationMax": 30,"hasResolution": true,"presetField": "mode"},
    "grok-imagine-video-1-5-preview": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "happyhorse/image-to-video": {"durationKind": "number","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "happyhorse/reference-to-video": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image","imageRefKind": "array"},
    "happyhorse/text-to-video": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true},
    "happyhorse/video-edit": {"hasResolution": true,"imageRefField": "reference_image","imageRefKind": "array","videoRefField": "video_url","videoRefKind": "single"},
    "happyhorse-1-1/text-to-video": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true},
    "happyhorse-1-1/image-to-video": {"durationKind": "number","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "single_array"},
    "happyhorse-1-1/reference-to-video": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image","imageRefKind": "array"},
    "minimax-h3/text-to-video": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 4,"durationMax": 15,"hasResolution": true,"resolutionKind": "minimax_h3_video"},
    "minimax-h3/image-to-video": {"durationKind": "number","durationMin": 4,"durationMax": 15,"hasResolution": true,"resolutionKind": "minimax_h3_video","imageRefField": "first_frame_url","imageRefKind": "single"},
    "minimax-h3/reference-to-video": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 4,"durationMax": 15,"hasResolution": true,"resolutionKind": "minimax_h3_video","imageRefField": "reference_image_urls","imageRefKind": "array","videoRefField": "reference_video_urls","videoRefKind": "array","audioRefField": "reference_audio_urls","audioRefKind": "array"},
    "hailuo/02-image-to-video-standard": {"durationKind": "string","hasResolution": true,"resolutionKind": "hailuo_video","imageRefField": "image_url","imageRefKind": "single"},
    "hailuo/02-image-to-video-pro": {"durationKind": "string","hasResolution": true,"resolutionKind": "hailuo_video","imageRefField": "image_url","imageRefKind": "single"},
    "hailuo/02-text-to-video-standard": {"durationKind": "string"},
    "hailuo/02-text-to-video-pro": {"durationKind": "string"},
    "hailuo/2-3-image-to-video-pro": {"durationKind": "string","hasResolution": true,"resolutionKind": "hailuo_video","imageRefField": "image_url","imageRefKind": "single"},
    "hailuo/2-3-image-to-video-standard": {"durationKind": "string","hasResolution": true,"resolutionKind": "hailuo_video","imageRefField": "image_url","imageRefKind": "single"},
    "kling-2.6/image-to-video": {"durationKind": "string","imageRefField": "image_urls","imageRefKind": "array"},
    "kling-2.6/text-to-video": {"aspectField": "aspect_ratio","durationKind": "string"},
    "kling-2.6/motion-control": {"durationKind": "string","imageRefField": "input_urls","imageRefKind": "array","videoRefField": "video_urls","videoRefKind": "array"},
    "kling-3.0/motion-control": {"durationKind": "string","imageRefField": "input_urls","imageRefKind": "array","videoRefField": "video_urls","videoRefKind": "array"},
    "kling-3.0/video": {"aspectField": "aspect_ratio","durationKind": "string","presetField": "mode","imageRefField": "image_urls","imageRefKind": "array"},
    "kling-3.0-omni/text-to-video": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 3,"durationMax": 15,"hasResolution": true},
    "kling-3.0-omni/image-to-video": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 3,"durationMax": 15,"hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "kling-3.0-omni/reference-to-video": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 3,"durationMax": 15,"hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array","videoRefField": "video_urls","videoRefKind": "array"},
    "kling-3.0-omni/transformation": {"aspectField": "aspect_ratio","durationKind": "number","durationMin": 3,"durationMax": 15,"hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array","videoRefField": "video_urls","videoRefKind": "array"},
    "kling/v3-turbo-text-to-video": {"aspectField": "aspect_ratio","durationKind": "string","hasResolution": true},
    "kling/v3-turbo-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "kling/ai-avatar-standard": {"imageRefField": "image_url","imageRefKind": "single","audioRefField": "audio_url","audioRefKind": "single"},
    "kling/ai-avatar-pro": {"imageRefField": "image_url","imageRefKind": "single","audioRefField": "audio_url","audioRefKind": "single"},
    "kling/v2-1-master-image-to-video": {"durationKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "kling/v2-1-master-text-to-video": {"aspectField": "aspect_ratio","durationKind": "string"},
    "kling/v2-1-pro": {"durationKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "kling/v2-1-standard": {"durationKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "kling/v2-5-turbo-image-to-video-pro": {"durationKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "kling/v2-5-turbo-text-to-video-pro": {"aspectField": "aspect_ratio","durationKind": "string"},
    "wan/2-2-a14b-image-to-video-turbo": {"hasResolution": true,"imageRefField": "image_url","imageRefKind": "single"},
    "wan/2-2-a14b-speech-to-video-turbo": {"hasResolution": true,"imageRefField": "image_url","imageRefKind": "single","audioRefField": "audio_url","audioRefKind": "single"},
    "wan/2-2-a14b-text-to-video-turbo": {"aspectField": "aspect_ratio","hasResolution": true},
    "wan/2-2-animate-move": {"hasResolution": true,"imageRefField": "image_url","imageRefKind": "single","videoRefField": "video_url","videoRefKind": "single"},
    "wan/2-2-animate-replace": {"hasResolution": true,"imageRefField": "image_url","imageRefKind": "single","videoRefField": "video_url","videoRefKind": "single"},
    "wan/2-5-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_url","imageRefKind": "single"},
    "wan/2-5-text-to-video": {"aspectField": "aspect_ratio","durationKind": "string","hasResolution": true},
    "wan/2-6-flash-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "wan/2-6-flash-video-to-video": {"durationKind": "string","hasResolution": true,"videoRefField": "video_urls","videoRefKind": "array"},
    "wan/2-6-image-to-video": {"durationKind": "string","hasResolution": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "wan/2-6-text-to-video": {"durationKind": "string","hasResolution": true},
    "wan/2-6-video-to-video": {"durationKind": "string","hasResolution": true,"videoRefField": "video_urls","videoRefKind": "array"},
    "wan/2-7-image-to-video": {"durationKind": "number","hasResolution": true,"imageRefField": "first_frame_url","imageRefKind": "single","videoRefField": "first_clip_url","videoRefKind": "single","audioRefField": "driving_audio_url","audioRefKind": "single"},
    "wan/2-7-r2v": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image","imageRefKind": "array","videoRefField": "reference_video","videoRefKind": "array","audioRefField": "reference_voice","audioRefKind": "single"},
    "wan/2-7-text-to-video": {"aspectField": "ratio","durationKind": "number","hasResolution": true,"audioRefField": "audio_url","audioRefKind": "single"},
    "wan/2-7-videoedit": {"aspectField": "aspect_ratio","durationKind": "number","hasResolution": true,"imageRefField": "reference_image","imageRefKind": "single","videoRefField": "video_url","videoRefKind": "single"},
    "bytedance/seedream": {"aspectField": "image_size","aspectKind": "image_size_named"},
    "bytedance/seedream-v4-edit": {"aspectField": "image_size","aspectKind": "image_size_named","resolutionField": "image_resolution","resolutionKind": "image","countField": "max_images","imageRefField": "image_urls","imageRefKind": "array"},
    "bytedance/seedream-v4-text-to-image": {"aspectField": "image_size","aspectKind": "image_size_named","resolutionField": "image_resolution","resolutionKind": "image","countField": "max_images"},
    "flux-2/flex-image-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","maxResolution": "2K","imageRefField": "input_urls","imageRefKind": "array"},
    "flux-2/flex-text-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","maxResolution": "2K"},
    "flux-2/pro-image-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","maxResolution": "2K","imageRefField": "input_urls","imageRefKind": "array"},
    "flux-2/pro-text-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","maxResolution": "2K"},
    "gpt-image-2-image-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","imageRefField": "input_urls","imageRefKind": "array"},
    "gpt-image-2-text-to-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image"},
    "nano-banana-2": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","hasOutputFormat": true,"imageRefField": "image_input","imageRefKind": "array"},
    "nano-banana-2-lite": {"aspectField": "aspect_ratio","imageRefField": "image_urls","imageRefKind": "array"},
    "nano-banana-pro": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","hasOutputFormat": true,"imageRefField": "image_input","imageRefKind": "array"},
    "wan/2-7-image": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","countField": "n","imageRefField": "input_urls","imageRefKind": "array"},
    "wan/2-7-image-pro": {"aspectField": "aspect_ratio","hasResolution": true,"resolutionKind": "image","countField": "n","imageRefField": "input_urls","imageRefKind": "array"},
    "google/imagen4": {"aspectField": "aspect_ratio"},
    "google/imagen4-fast": {"aspectField": "aspect_ratio"},
    "google/imagen4-ultra": {"aspectField": "aspect_ratio"},
    "google/nano-banana": {"aspectField": "aspect_ratio","hasOutputFormat": true},
    "google/nano-banana-edit": {"aspectField": "aspect_ratio","hasOutputFormat": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "gpt-image/1.5-image-to-image": {"aspectField": "aspect_ratio","hasQuality": true,"imageRefField": "input_urls","imageRefKind": "array"},
    "gpt-image/1.5-text-to-image": {"aspectField": "aspect_ratio","hasQuality": true},
    "grok-imagine-image-2-0/text-to-image": {"aspectField": "aspect_ratio"},
    "grok-imagine/text-to-image": {"aspectField": "aspect_ratio"},
    "grok-imagine/image-to-image": {"imageRefField": "image_urls","imageRefKind": "array"},
    "grok-imagine/extend": {"imageRefField": "image_url","imageRefKind": "single"},
    "ideogram/character": {"aspectField": "image_size","aspectKind": "image_size_named","countField": "num_images","countKind": "string","imageRefField": "reference_image_urls","imageRefKind": "array"},
    "ideogram/character-edit": {"countField": "num_images","countKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "ideogram/character-remix": {"aspectField": "image_size","aspectKind": "image_size_named","countField": "num_images","countKind": "string","imageRefField": "reference_image_urls","imageRefKind": "array"},
    "ideogram/v3-edit": {"imageRefField": "image_url","imageRefKind": "single"},
    "ideogram/v3-remix": {"aspectField": "image_size","aspectKind": "image_size_named","countField": "num_images","countKind": "string","imageRefField": "image_url","imageRefKind": "single"},
    "ideogram/v3-text-to-image": {"aspectField": "image_size","aspectKind": "image_size_named"},
    "qwen/text-to-image": {"aspectField": "image_size","aspectKind": "image_size_named","hasOutputFormat": true},
    "qwen/image-edit": {"aspectField": "image_size","aspectKind": "image_size_named","countField": "num_images","countKind": "string","hasOutputFormat": true,"imageRefField": "image_url","imageRefKind": "single"},
    "qwen/image-to-image": {"hasOutputFormat": true,"imageRefField": "image_url","imageRefKind": "single"},
    "qwen2/image-edit": {"aspectField": "image_size","hasOutputFormat": true,"imageRefField": "image_url","imageRefKind": "single"},
    "qwen2/text-to-image": {"aspectField": "image_size","hasOutputFormat": true},
    "recraft/crisp-upscale": {"imageRefField": "image","imageRefKind": "single"},
    "recraft/remove-background": {"imageRefField": "image","imageRefKind": "single"},
    "seedream/4.5-edit": {"aspectField": "aspect_ratio","hasQuality": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "seedream/4.5-text-to-image": {"aspectField": "aspect_ratio","hasQuality": true},
    "seedream/5-lite-image-to-image": {"aspectField": "aspect_ratio","hasQuality": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "seedream/5-lite-text-to-image": {"aspectField": "aspect_ratio","hasQuality": true},
    "seedream/5-pro-text-to-image": {"aspectField": "aspect_ratio","hasQuality": true},
    "seedream/5-pro-image-to-image": {"aspectField": "aspect_ratio","hasQuality": true,"imageRefField": "image_urls","imageRefKind": "array"},
    "seedream/5-pro-layer-decomposition": {"imageRefField": "image_url","imageRefKind": "single"},
    "topaz/image-upscale": {"imageRefField": "image_url","imageRefKind": "single"},
    "topaz/video-upscale": {"videoRefField": "video_url","videoRefKind": "single"},
    "infinitalk/from-audio": {"hasResolution": true,"imageRefField": "image_url","imageRefKind": "single","audioRefField": "audio_url","audioRefKind": "single"},
    "z-image": {"aspectField": "aspect_ratio"}
};
export const teamKIEModelAliases: Record<string, string> = {
    "seedream/seedream": "bytedance/seedream",
    "seedream/seedream-v4-text-to-image": "bytedance/seedream-v4-text-to-image",
    "seedream/seedream-v4-edit": "bytedance/seedream-v4-edit",
    "seedream/4-5-text-to-image": "seedream/4.5-text-to-image",
    "seedream/4-5-edit": "seedream/4.5-edit",
    "z-image/z-image": "z-image",
    "google/nanobanana2": "nano-banana-2",
    "google/nano-banana-2-lite": "nano-banana-2-lite",
    "google/pro-image-to-image": "nano-banana-pro",
    "flux2/pro-image-to-image": "flux-2/pro-image-to-image",
    "flux2/pro-text-to-image": "flux-2/pro-text-to-image",
    "flux2/flex-image-to-image": "flux-2/flex-image-to-image",
    "flux2/flex-text-to-image": "flux-2/flex-text-to-image",
    "gpt-image/1-5-text-to-image": "gpt-image/1.5-text-to-image",
    "gpt-image/1-5-image-to-image": "gpt-image/1.5-image-to-image",
    "gpt/gpt-image-2-text-to-image": "gpt-image-2-text-to-image",
    "gpt/gpt-image-2-image-to-image": "gpt-image-2-image-to-image",
    "bytedance/seedance-1-5-pro": "bytedance/seedance-1.5-pro",
    "kling/text-to-video": "kling-2.6/text-to-video",
    "kling/image-to-video": "kling-2.6/image-to-video",
    "kling/motion-control": "kling-2.6/motion-control",
    "kling/motion-control-v3": "kling-3.0/motion-control",
    "kling/kling-3-0": "kling-3.0/video",
    "kling/v25-turbo-image-to-video-pro": "kling/v2-5-turbo-image-to-video-pro",
    "kling/v25-turbo-text-to-video-pro": "kling/v2-5-turbo-text-to-video-pro",
    "grok-imagine/1-5-preview": "grok-imagine-video-1-5-preview",
    "grok-imagine/grok-imagine-1.5-preview": "grok-imagine-video-1-5-preview"
};
